Aug 30 18:36:11 ubuntu-s-1vcpu-1gb-sgp1-01 python[292086]: Traceback (most recent call last):
Aug 30 18:36:11 ubuntu-s-1vcpu-1gb-sgp1-01 python[292086]:   File "/home/uaft/uaft_project_50lite/tg_runner.py", line 60, in main
Aug 30 18:36:11 ubuntu-s-1vcpu-1gb-sgp1-01 python[292086]:     res = AI.route(event)  # ожидаем dict
Aug 30 18:36:11 ubuntu-s-1vcpu-1gb-sgp1-01 python[292086]: AttributeError: module 'ai_supervisor' has no attribute 'route'
Aug 30 18:38:56 ubuntu-s-1vcpu-1gb-sgp1-01 python[292640]: === UAFT tg_runner started ===
Aug 30 18:39:18 ubuntu-s-1vcpu-1gb-sgp1-01 python[292640]: LLM fallback failed: Error code: 400 - {'error': {'message': "Unsupported value: 'temperature' does not support 0.6 with this model. Only the default (1) value is supported.", 'type': 'invalid_request_error', 'param': 'temperature', 'code': 'unsupported_value'}}
